class ProgramGenerator:
    def __init__(self, gemini_client):
        self.gemini_client = gemini_client

    def generate_program(self, prompt: str) -> str:
        """
        Generates a program based on the provided prompt using Gemini.

        Args:
            prompt: The prompt generated by the EvolvePromptGenerator.

        Returns:
            The generated program code string.
        """
        # This is a placeholder implementation.
        # In a real implementation, you would call self.gemini_client.generate_text(prompt)
        # and parse the output to extract the code block.
        print("Generating program with Gemini (placeholder)...")
        print(f"Prompt:\n{prompt}")

        # Dummy program code
        dummy_code = """
def example_function(input):
    # This is a dummy program
    return input * 2
"""
        print(f"Generated dummy program:\n{dummy_code}")
        return dummy_code
